source "http://ruby.taobao.org"

gem "rake"

# ProMotion
gem "ProMotion", "~> 2.0"
gem 'bubble-wrap'
 # '0.18.6'
# gem 'formotion', :git => 'https://github.com/clayallsopp/formotion.git'
gem 'motion-cocoapods', '~> 1.4.1'
gem 'cocoapods', '~> 0.32.1'
gem 'nano-store'

